### ISSUE TITLE
Enable Amazon Time Sync on hyperbola-app AMI

### ISSUE THREAD

**Issue by lopopolo** [lopopolo/hyperbola#79]
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html
- https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/
- https://github.com/geerlingguy/ansible-role-ntp

should be able to add the ansible role to requirements.yaml and include it as a dep of hyperbola-base like this:

```yaml
---
dependencies:
- role: hswong3i.tzdata
  tzdata_timezone: Etc/UTC
- role: geerlingguy.security
- role: geerlingguy.ntp
  ntp_timezone: Etc/UTC
  ntp_manage_config: true
  ntp_servers:
  - "169.254.169.123 prefer iburst"
  when: "{{ hyperbola_environment == 'production' }}"
```
